name: EUNL Yearly Holdings

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 5 3 * *'  # optional: jeweils am 3. des Monats 05:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clone talsan/ishares (scraper)
        run: |
          git clone --depth 1 https://github.com/talsan/ishares.git vendor/ishares
          ls -la vendor/ishares

      # 🔧 WICHTIGER FIX: altes lxml==4.5.1 auf eine Py3.11-kompatible Version setzen
      - name: Patch vendor requirements (lxml pin)
        run: |
          sed -i 's/^lxml==4\.5\.1$/lxml==4.9.4/' vendor/ishares/requirements.txt
          echo "Patched requirements.txt:"
          grep -n 'lxml' vendor/ishares/requirements.txt || true

      - name: Install dependencies (incl. vendor requirements)
        run: |
          python -m pip install --upgrade pip
          pip install -r vendor/ishares/requirements.txt
          pip install pandas pyarrow requests python-dateutil

      - name: Sanity check import
        run: |
          PYTHONPATH=vendor/ishares python - <<'PY'
          from ishares.etf_downloader import get_etf_index
          idx = get_etf_index()
          print("Index rows:", len(idx))
          PY

      - name: Fetch full SWDA holdings history (module import fix)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -euxo pipefail
          PYTHONPATH=vendor/ishares python -m ishares.sync_etf_downloader \
            --outputpath data/ishares \
            SWDA \
            --overwrite

      - name: Verify downloaded files
        run: |
          echo "Listing a few downloaded CSVs…"
          ls -R data/ishares | head -n 200 || true

      - name: Select latest snapshot per year (>= 2010)
        run: |
          python scripts/select_yearly_snapshots.py \
            --root data/ishares \
            --etf SWDA \
            --from-year 2010 \
            --outdir exports/eunl_yearly

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eunl_yearly_exports
          path: exports/eunl_yearly

      - name: Commit & push results back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add exports/eunl_yearly summary/* || true
          if ! git diff --cached --quiet; then
            git commit -m "Update EUNL yearly holdings exports"
            git push
          else
            echo "No changes to commit"
          fi
